backend:
  name: git-gateway
  branch: main

media_folder: public/images/uploads
public_folder: /images/uploads

publish_mode: simple

collections:
  - name: board
    label: 게시판
    folder: content/board
    create: true
    slug: '{{year}}{{month}}{{day}}-{{slug}}'
    fields:
      - { label: 제목, name: title, widget: string, required: true }
      - {
          label: 작성일,
          name: date,
          widget: datetime,
          format: YYYY-MM-DD,
          date_format: YYYY-MM-DD,
          time_format: false,
          default: now,
        }
      - { label: 작성자, name: author, widget: string, required: true }
      - {
          label: 썸네일 이미지,
          name: thumbnail,
          widget: image,
          required: false,
        }
      - {
          label: 첨부 이미지들,
          name: images,
          widget: list,
          required: false,
          fields: [{ label: 이미지, name: image, widget: image }],
        }
      - { label: 내용, name: body, widget: markdown, required: true }
    sortable_fields:
      - commit_date
      - title
      - date
      - author

  - name: pages
    label: 페이지
    folder: content/pages
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 제목, name: title, widget: string, required: true }
      - { label: 내용, name: body, widget: markdown, required: true }
    sortable_fields:
      - commit_date
      - title
      - commit_author
