backend:
  name: github
  repo: cau-filmstudies/film-studies-site
  branch: main
  auth_scope: repo
  client_id: Ov23libaKgVihLREnBGa
  base_url: https://api.netlify.com

media_folder: public/images/uploads
public_folder: /images/uploads

publish_mode: simple

collections:
  - name: board
    label: 게시판
    folder: content/board
    create: true
    slug: '{{year}}{{month}}{{day}}-{{slug}}'
    fields:
      - { label: 제목, name: title, widget: string, required: true }
      - {
          label: 작성일,
          name: date,
          widget: datetime,
          format: YYYY-MM-DD,
          date_format: YYYY-MM-DD,
          time_format: false,
          default: now,
        }
      - { label: 작성자, name: author, widget: string, required: true }
      - { label: 내용, name: body, widget: markdown, required: true }
    sortable_fields:
      - commit_date
      - title
      - date
      - author

  - name: pages
    label: 페이지
    folder: content/pages
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 제목, name: title, widget: string, required: true }
      - { label: 내용, name: body, widget: markdown, required: true }
    sortable_fields:
      - commit_date
      - title
      - commit_author
